version: '3.8'

services:
  docker-goat:
    build: .
    container_name: docker-goat-container
    ports:
      - '8080:80'
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./sitio:/usr/share/nginx/html:ro
    networks:
      - docker-goat-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  docker-goat-network:
    driver: bridge
    name: docker-goat-net
# Opcional: Para desarrollo con volúmenes de desarrollo
# Descomenta las siguientes líneas si quieres desarrollo en tiempo real
# volumes:
#   docker-goat:
#     external: false
